os: osx
osx_image: xcode8.3
language: cpp
compiler: gcc

env:
  global:
  - LDFLAGS=-L/usr/local/opt/openssl/lib
  - CPPFLAGS=-I/usr/local/opt/openssl/include

before_install:
- brew update
- brew unlink boost python
- brew bundle
- brew link boost@1.57 --force

script:
- "./autogen.sh"
- "./configure"
- make deploy
before_deploy:
- git config --local user.name "methuselahdev"
- git config --local user.email "methuselahdev@gmail.com"
- git tag "methuselah-test-1.1.0.0"
- echo `pwd`

deploy:
  provider: releases
  api_key:
    secure: b9zII6FoG6BJhi1Dg32Or+9hITfSXYUOLlOf3v+q5e3t8HluktBpIkajI8hLY7VJAzMmmDJ+zzdnQCFAHe5BfjPJjU7q8TsLYL4xH8mMR5U06om4Ns7Mt5MjzDoKsHP0t/+fYWNJIWGaC0pr2mY7CZG5NfSbRoV7Q/xO1Ujx+lszEqcs78bPBT9/cjDxW398f/dqxlFzOb+sX7QqXbbsbaLbmcT+60bhLMH0SGw4HAKAOlxmmR/y+7ic+2EZe1UXTuoZY5xBnjVrd6Kid8cz1UGzzYGk1N6Sc7wH/Xg6QAi+JBD1NFIJiembhVEs1vLQUOa/C+eCeRT11KOVMo2fRsNuRNT2DgJ8jNWRy/2MgJ59kheDqDTHkeMul1fTW5K3qHEYZ0lDUYy8DdoagoN6EPpJfjQVg/OQSwoLz+4jZfSsrVH/vAoEuP4cDEsZUkQ/aXmtxKMOhkeUrf9gV/Yn2CENsf5Yp6QK8BXdS+Rp6Fdkzga12RVCgFcLMYJ61k50f8Bav15eP7piEpTX7NmfpqjLtWjlzEcUZqhkwPWr1+vKkaQsARb7RMPwfP4F7j3fYzGXweY2lbIXYmaYD3EVNFlnltHcC1WpMzAnbrgDalaIDE1n3KstpLzZKTRF840uGS0OGQBOkqxnGgPyLgExpKO0OL693ebwjsSQWak4n+U=
  skip_cleanup: true
  file_blob: true  
  file: Methuselah-QT.dmg
  overwrite: true
  on:
    repo: methuselahdev/methuselah
    branch: osx-build
