os: osx
osx_image: xcode8.3
language: cpp
compiler: gcc
env:
  global:
  - LDFLAGS=-L/usr/local/opt/openssl/lib
  - CPPFLAGS=-I/usr/local/opt/openssl/include
before_install:
- brew update
- brew unlink boost python
- brew bundle
- brew link boost@1.57 --force
script:
- "./autogen.sh"
- "./configure"
- make deploy
before_deploy:
- git config --local user.name "methuselahdev"
- git config --local user.email "methuselahdev@gmail.com"
- git tag "methuselah-1.1.0.3"
- echo `pwd`
deploy:
  provider: releases
  api_key:
    secure: FzfIpkdPVi3NjCDdVYaNII9Zw/h2A9qaBtEMyXSMig8gMY6DdmRiExZC4IROwND2qdWA7CNsUZQ+mS8E4RnpQzMjmMgF0hqdTRBg63bXQ1yGsqdFEENgvD9wAJoQz2YdwFaTZklEYvZkExfc6Wesl/LpaGUIlV2J9PstSdyvSpJyGUD4dZ3orH2xbY9BClXhRvfzenstQXrzS5kfxhMR9VXu1ykEcBcZ+GWwQNF9qPClgyRpxKDO4uCgm6obZ+DnKT2cfaC3aZBCNKEY6b0xAUHNfXp2re26/xaqraUWhQd3C3NikOM6atWyIU/E9bH67co8UY7Jhtoy9kV4ug7h+fPf0ExYzRhNyaDJJXtJYAcWkwK64OcymqiNdmVWUHEO0dr1YwWCMb53LSTmSbveAM4024S4WEGm8ksXpeQjHl3NtnF+/j5UknHmQN+fT0y1z7xb8+sfG8Wc5gBTM+WhBRMNvcL9Kc4g9xGa7X4aEj/hiOZaZfnJzIKJ9EYXzIhWHVYb0gpv9VUR4yoYfuvlLgd3+TgMQzppnNPiWxq8gYHpAoQWqjDKREQZbgsqZSrWn6KZvLTfaJMuEi1+1TXbiQJk3fjVt8UCZ/jmWF+YG5RwaUQFi77Da6M6NZuBjj4/Tbi774wM4mtuz1MBc/kwAo015Nov1yB76xm3gY8jePY=
  file: Methuselah-QT.dmg
  overwrite: true
  skip_cleanup: true
  on:
    repo: methuselahdev/methuselah
    branch: master

